version: "3.9"
services:
  # python-app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8000:8000"
  go-app:
    build:
      context: .
      dockerfile: Dockerfile-go
    ports:
      - "18080:8080"
