[project]
name = "mcp-server"
version = "0.1.0"
description = "learn to make some mcp servers"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mcp[cli]>=1.4.1",
    "requests>=2.32.3",
]
